### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by rgocal** [zhanghai/AndroidFastScroll#10]
The drawable is invisible and the Fastscroll only shows my first letter of the list. What should i be looking at to fix this.

**Comment by zhanghai** [comment]
I don't have an idea with the info you provided.

**Comment by rgocal** [comment]
What do you wanna know. I figured it was an easy installation and followed instructions

**Comment by rgocal** [comment]
The added the Fastscroll just like your example to my recycleview. The popup drawable is transparent and the slider only shows one letter and the first letter of the list.

**Comment by creati8e** [comment]
Confirm. Track and thumb are not visible on Android 5

**Comment by zhanghai** [comment]
This will likely be fixed by 5c21552. Thanks to @RikkaW!
