### ISSUE TITLE
In Recyclerview with large data set, button will not go to bottom of list

### ISSUE THREAD

**Issue by PeterParker135** [zhanghai/AndroidFastScroll#12]
I can provide any info or samples you need.

This is pretty easy to reproduce:

Create a vertical recyclerview with a lot of items (1 page in my project has 3447 items), try fast scrolling to the bottom.

In current data set, thumb will not go lower than position 3433.

Recyclerview item height is set to ?listPreferredItemHeightSmall

Please let me know if need any other info

**Comment by zhanghai** [comment]
Did you try version 1.1.1? I fixed an issue about integer overflow.

**Comment by PeterParker135** [comment]
This is on 1.1.1

**Comment by zhanghai** [comment]
I duplicated the locale list in sample app for 100 times, which gives 72400 list items, and fast scrolling still worked well. Could you try to reproduce your issue with sample app and post your reproduction steps here?

Meanwhile, note that this library doesn' support variable item height out-of-the-box, and you need to implement your own `ViewHelper` to do that.

**Comment by PeterParker135** [comment]
I'm very sorry, I should have mentioned that the list is in a viewpager2 with a tabLayout.

If I remove the tabs.  It works as expected.  How do I accommodate the tablayout?

**Comment by PeterParker135** [comment]
After stripping out everything related to fast scroll but leaving the tablayout, I find it's still cutting off the last 2 items, so I don't think it's an issue with this lib.

If you have any insight on that, I'd be more than happy to hear it, otherwise I believe you can close this issue :)
