### ISSUE TITLE
Staggered gird list

### ISSUE THREAD

**Issue by pereved** [zhanghai/AndroidFastScroll#16]
Please do support Staggered gird list.

When changing the layout manager to staggered gird layout manager, fast scroller stops working and just disappears.

## Actual Behavior

Does not work

## Steps to Reproduce the Problem

1. Change layout manager to Staggered gird layout manager.

## Specifications

- Version: Any
- Platform: Any

**Comment by zhanghai** [comment]
Only the app developer knows how big each of their list items should be, and there is no general way for a library to guess it, so the library only supports items of the same height out-of-the-box in [`RecyclerViewHelper`](https://github.com/zhanghai/AndroidFastScroll/blob/master/library/src/main/java/me/zhanghai/android/fastscroll/RecyclerViewHelper.java). You'll need to implement your own `FastScroller.ViewHelper` to help `FastScroller` scroll to the desired position.
