### ISSUE TITLE
Provide an alternate way to set PopupTextProvider

### ISSUE THREAD

**Issue by RobbWatershed** [zhanghai/AndroidFastScroll#19]
I'm using the latest version of the `AndroidFastScroll` in conjunction with the `FastAdapter` library.

Since I cannot customize the implementation of my adapter class, I would like to have an alternate way of providing a standalone `PopupTextProvider`.

How about providing it as an argument to `FastScrollerBuilder` ?  I can suggest a PR if you want...

**Comment by eamiguinho** [comment]
This will be incredibly helpful because we use Epoxy Library from Airbnb and we had to do some changes to be able to use adapters to implement the provider. @zhanghai thoughts?

**Comment by zhanghai** [comment]
Added `FastScrollerBuilder.setPopupTextProvider()`.

**Comment by RobbWatershed** [comment]
Works like a charm ! Thanks a lot
