### ISSUE TITLE
Change Md2PopupBackground class modifier

### ISSUE THREAD

**Issue by kimcy929** [zhanghai/AndroidFastScroll#2]
I want to custom PopupStyles MD2 textColor is white color in Kotlin (1.3.50). But currently, I can't access Md2PopupBackground because it missing modifier **public** . Can you make it is public or support a PopupStyles.Builder that allow custom somethings as textColor, backgroundColor...

Cannot access 'Md2PopupBackground': it is public/*package*/ in 'me.zhanghai.android.fastscroll'

![image](https://user-images.githubusercontent.com/4311848/68283067-775ac100-00ad-11ea-8bf6-078f0aba19a2.png)

Thanks!

**Comment by zhanghai** [comment]
You can simply do:

```kotlin
val popupStyle = Consumer<TextView> { popupView ->
    PopupStyles.Md2.accept(popupView)
    popupView.setTextColor(Color.WHITE)
}
```

I thought over it a bit and decided `Md2PopupBackground` shouldn't be an API of this library. It isn't a fully functional `Drawable` and things like `setAlpha()` and `setColorFilter()` are missing. If people want to use it, they can make their own copy, or in a hacky and less stable way, call `popupView.getBackground()` after `PopupStyles.Md2` is applied.

**Comment by kimcy929** [comment]
Thank you! I try it out.

**Comment by gmzt023** [comment]
How to change only popup and thumb color?
