### ISSUE TITLE
Support scrollbar location override instead of using view layout direction

### ISSUE THREAD

**Issue by glenn-mcgregor** [zhanghai/AndroidFastScroll#20]
## Expected Behavior

Feature motivation...

I have a left-handed user that would like the scrollbar on the left hand side, even when the text and layouts are in LTR mode.

Ideally, some sort of setting on the FastScrollerBuilder that would eventually cause the onPreDraw to use this override instead view.getLayoutDirection.

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version: 1.1.4
- Platform: Android

**Comment by zhanghai** [comment]
As long as the system scrollbar implementation doesn't have dedicated support for drawing scrollbar on the left in LTR, I don't think this is something this library should aim to support.
