### ISSUE TITLE
Don't show scroll handle on first start [hacky solution]

### ISSUE THREAD

**Issue by mhettig** [zhanghai/AndroidFastScroll#24]
I want to create a behavior where the fast scroll handle isn't shown on app start but when first scrolling. The goal is to have a cleaner and minimalistic look. Normal hide animation should be uneffected.

Without changing the library itself I came up with the hacky workaround at the bottom. Maybe this can be helpful for someone, so I want to share it with you.

_Is this maybe a valid feature request implementing this directly into the library?_ (Used version here: 1.1.4)

```kotlin
/**
 * Hides the fast scroll handle on init, so it's first visible after scrolling.
 */
class HideOnInitAnimationHelper(view: View) : DefaultAnimationHelper(view) {
    private var firstRun = true

    override fun getScrollbarAutoHideDelayMillis(): Int {
        return if (firstRun) {
            0
        } else {
            super.getScrollbarAutoHideDelayMillis()
        }
    }

    override fun showScrollbar(trackView: View, thumbView: View) {
        // Assumption: showScrollbar() is only called once during initialization
        if (firstRun) {
            firstRun = false
            return
        }

        super.showScrollbar(trackView, thumbView)
    }

    override fun hideScrollbar(trackView: View, thumbView: View) {
        if (firstRun) {
            trackView.alpha = 0f
            thumbView.alpha = 0f
        }

        super.hideScrollbar(trackView, thumbView)
    }
}
```

**Comment by zhanghai** [comment]
The original behavior is working as intended because it serves as a visual indicator to user that content can be scrolled. This is important in cases where the last visible item happens to be aligned with bottom of screen, and is the same behavior as framework scrollbar.

**Comment by mhettig** [comment]
That is a valid point. I am aware that this a downside and a good reason to not implement such a behavior in the library. Thank you for the fast answer.
