### ISSUE TITLE
Is it posible to activate fastscrolling only on thumb click, not the entire track?

### ISSUE THREAD

**Issue by alecpetrosky** [zhanghai/AndroidFastScroll#25]
## Expected Behavior

You click thumb, it has current behaviour. You click the track outside of thumb and it does not react. One of the examples of expected behavior could be Google Photos fast track.

## Actual Behavior

Thumb follows your click in any track area.

**Comment by zhanghai** [comment]
No, this library is designed to allow clicks in track area, and Google Contacts app has the same behavior. Google Photos isn't really using a standard fast scroller so I believe Google Contacts is a better example to follow.
