### ISSUE TITLE
Random change position when taking your finger out of fastscroll thumb

### ISSUE THREAD

**Issue by alecpetrosky** [zhanghai/AndroidFastScroll#26]
## Expected Behavior

You finish fastscrolling, take your hand out of fastscroller, recyclerview's position stays still.

## Actual Behavior

You finish fastscrolling, take your hand out of fastscroller, recyclerview's position jumps up or down. It maybe no problem when you have only 100-200 elements but when you have 50k-100k you may end 100-200 elements up or down from the original position that you had before taking your hand from fastscroller.

## Steps to Reproduce the Problem

1. Fast scroll having your finger on fastscroll thumb.
1. Take your finger from thumb.
1. 90% of times recyclerview will jump.

**Comment by alecpetrosky** [comment]
I perfectly understand the reason why fastscroller acts in such manner but maybe we could check if onmove delta X > delta Y and this way we could decide that the user's intention is stop scrolling?

**Comment by zhanghai** [comment]
Why would deltaX be greater than deltaY when user stops scrolling? I personally just lift my finger from screen when I want to stop scrolling, and I don't see a reason to expect invalid X movement to be significant greater than y movement.

**Comment by alecpetrosky** [comment]
It was my guess and just observation of my scrolling micro-movements at the moment of stop scrolling and lifting my finger. If I lift it it goes much more to the right than up or down. Do you have more ideas how we could catch this moment? I know it's a bit tricky and lots of programs leave it as is. But it's quite a bit annoying for the user.  Again, both Google Photos and Samsung Gallery don't have this glitch.

**Comment by zhanghai** [comment]
Sorry, I don't have a good idea about this :/
