### ISSUE TITLE
Support nesting RecyclerView in SwipeRefreshLayout

### ISSUE THREAD

**Issue by hansenji** [zhanghai/AndroidFastScroll#28]
## Expected Behavior
Fast Scrolling up or down doesn't trigger swipe refresh.

## Actual Behavior
Fast Scrolling down triggers SwipeRefresh

## Steps to Reproduce the Problem

1. Place RecyclerView inside of SwipeRefreshLayout
1. Add FastScroller
1. Trying to scroll down always triggers SwipeRefresh

## Specifications

- Version: 1.1.4
- Platform: Android RecyclerView 1.2.0-alpha02

**Comment by zhanghai** [comment]
[zhanghai/MaterialFiles](https://github.com/zhanghai/MaterialFiles) uses`SwipeRefreshLayout` + `RecyclerView` + `FastScroller` without a problem. Can you check if there is anything special within your own setup?

**Comment by hansenji** [comment]
I have a 
CoordinatorLayout
 - AppBarLayout
 - SwipeRefreshLayout
   - FrameLayout
   - RecyclerView

The frame layout is required to keep the recyclerview from going under the AppbarLayout.

**Comment by zhanghai** [comment]
`SwipeRefreshLayout` can only host one direct child (a [source](https://stackoverflow.com/questions/23830594/)). You may solve your problem by adding top margin to your `SwipeRefreshLayout` instead of adding a `FrameLayout` inside it.
