### ISSUE TITLE
Publish artifacts to Maven Central

### ISSUE THREAD

**Issue by msfjarvis** [zhanghai/AndroidFastScroll#35]
JFrog has made the decision to [shut down Bintray](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) on May 1st 2021 which means libraries that are only available on JCenter will stop resolving for users. It'd be greatly appreciated if this library is also published to the [Sonatype OSS repository](https://repo1.maven.org/maven2/) so that projects can continue depending on it after JCenter is gone.

**Comment by msfjarvis** [comment]
Hey @zhanghai can you take a look at this sometime soon? Thanks!

**Comment by msfjarvis** [comment]
@zhanghai Hey, are you planning to work on this anytime soon?

**Comment by MuntashirAkon** [comment]
You can use Jitpack in the meantime:
```groovy
implementation 'com.github.zhanghai:AndroidFastScroll:v1.1.5'
```

**Comment by zhanghai** [comment]
You don't have to worry - Although Bintray is shutting down today, they have promised JCenter to stay online (read-only) indefinitely. The next version of this library will be on Maven Central, but before that, the read-only JCenter is still better than JitPack.

**Comment by AndroidDeveloperLB** [comment]
@zhanghai Can you please write here after you publish to mavenCentral ?

**Comment by zhanghai** [comment]
Sure, let me reopen this.

**Comment by AndroidDeveloperLB** [comment]
@zhanghai Thank you very much!

**Comment by zhanghai** [comment]
Done.
