### ISSUE TITLE
android:tint in GradientDrawable

### ISSUE THREAD

**Issue by huaxunhuang** [zhanghai/AndroidFastScroll#36]
Hi,

I just found your commit 91a796a to fix the android:tint issues at API level 21. But it seems that you did not workaround for afs_thumb_stateful in RecyclerViewListStatefulFragment.java by changing the method call, which can still induce the issue.

**Comment by zhanghai** [comment]
Yes, that's correct, I've already talked about this in that commit:

```
                // It was later discovered that the following XML drawable doesn't work on
                // Lollipop (API 21) due to the bug that GradientDrawable didn't actually implement
                // tinting until Lollipop MR1 (API 22). So if you need to support API 21, you'll
                // need to work around it yourself.
```
