### ISSUE TITLE
FixItemDecorationRecyclerView

### ISSUE THREAD

**Issue by MasterKali06** [zhanghai/AndroidFastScroll#37]
any sample on using FixItemDecorationRecyclerView for multiple decorators?
how we can draw it over other decorations with this method .. i mean to clarify it more how to bring fast scroller on top of every other view in the recycler view?
i will appreciate any help thanks ...

**Comment by zhanghai** [comment]
What happens if you just replace your `RecyclerView` with `FixItemDecorationRecyclerView` and add the other `ItemDecoration`s as usual?

**Comment by MasterKali06** [comment]
wrote my own FastScroller within past 10 hours :)
but now i see that this would have resolve my issue ... works perfectly fine if you replace RecyclerView with FixItemDecorationRecyclerView
you can have multiple decorations with scroller on top of them.
thanks
