### ISSUE TITLE
Unwanted visualize effect + jumpy effect when applying AndroidFastScroll on RecyclerView

### ISSUE THREAD

**Issue by yccheok** [zhanghai/AndroidFastScroll#40]
Hi Zhang Hai,

I am currently using 1.1.7

I can appreciate your library over AndroidX's RecyclerView's `app:fastScrollEnabled` implementation due to

- Your library provide a wider touch region for thumb. Hence, it is easier to hit rect the thumb.
- Your library will make the touch point stay correctly on thumb. For instance, if we touch on the vertical center of the thumb. After fast scrolling, our touch point will remain on the center of thumb. 

The following is the AndroidX's implementation, which doesn't respect the initial touch point of thumb - https://www.youtube.com/watch?v=c9jkI7ryyoA In AndroidX's example, our initial touch point is the center of the thumb. However, after fast scrolling, our touch point will no longer stay at the center of thumb

Here's the AndroidX's implementation

    app:fastScrollEnabled="true"
    app:fastScrollVerticalThumbDrawable="@drawable/fast_scroll_thumb_material_light"
    app:fastScrollVerticalTrackDrawable="@drawable/fast_scroll_track_material_light"
    app:fastScrollHorizontalThumbDrawable="@drawable/fast_scroll_thumb_material_light"
    app:fastScrollHorizontalTrackDrawable="@drawable/fast_scroll_track_material_light"

When I port to your library, I am happy to see it

- Respect initial touch point of the thumb
- Provide wider touch region

However, it does yield some behaviour, which is previously not seen in AndroidX

- When scroll to the top most, the scroll bar will disappear. When scroll to the bottom most, there is an unwanted padding - https://www.youtube.com/watch?v=veIfuR9eUrk

- After scroll to the top most and scroll bar disappear, scroll again will produce "jumpy" effect - https://youtu.be/BmJF2nRsGiE

I am using the exact same RecylerView configuration as when I use AndroidX

I do not have any bottom padding, or top padding on the RecyclerView itself.

This is my RecyclerView

    <androidx.recyclerview.widget.RecyclerView
        
        android:requiresFadingEdge="none"
        android:scrollbars="none"

        android:background="?attr/recyclerViewBackground"
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clipToPadding="false"
        android:paddingTop="0dp"
        android:paddingBottom="0dp" />

and this is the new code I have added

    FastScrollerBuilder fastScrollerBuilder = new FastScrollerBuilder(recyclerView);
    fastScrollerBuilder.setThumbDrawable(getResources().getDrawable(R.drawable.fast_scroll_thumb_material_light));
    fastScrollerBuilder.setTrackDrawable(getResources().getDrawable(R.drawable.fast_scroll_track_material_light));
    fastScrollerBuilder.build();

Do you have an idea what might go wrong, and where I can start to debug from?

Thank you very much!

p/s I just realize I am using your materialratingbar library too when I adding your AndroidFastScroll into build.gradle. Thank you!

**Comment by yccheok** [comment]
I did some simple debugging on the code.

By looking at

https://github.com/zhanghai/AndroidFastScroll/blob/master/library/src/main/java/me/zhanghai/android/fastscroll/RecyclerViewHelper.java#L84

and

https://github.com/zhanghai/AndroidFastScroll/blob/master/library/src/main/java/me/zhanghai/android/fastscroll/RecyclerViewHelper.java#L155

I assume the library is assuming every item in the recycler view is having same height, during scroll range computation.

However, in my https://www.youtube.com/watch?v=veIfuR9eUrk , which its top contain a label item, and an invisible small padding item, which are having different height than rest of the items.

This is causing the function

    private int getScrollOffsetRange() {
        return mViewHelper.getScrollRange() - mView.getHeight();
    }

to return a -ve value, even before the top is hit. `mViewHelper.getScrollRange()` taking computation based on label item/ invisible small padding item instead of regular content item.

By examing the code at https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/recyclerview/recyclerview/src/main/java/androidx/recyclerview/widget/FastScroller.java#445

Instead of using `mViewHelper.getScrollRange()`, is there a reason not to use `((RecyclerView)mView).computeVerticalScrollRange()` ?

Thank you.

**Comment by zhanghai** [comment]
Yes the default implementation doesn't support inconsistent item heights and it's documented in README. `computeVerticalScrollingRange()` won't return the actual height of all items, because that requires inflating every single item and measuring them. You may use the actual padding on the RecyclerView instead of an item for padding, or you may have to write your own `ViewHelper`, or use the AndroidX implementation which has different trade-offs and won't need to know the actual height.
