### ISSUE TITLE
支持PreferenceFragmentCompat

### ISSUE THREAD

**Issue by allentown521** [zhanghai/AndroidFastScroll#42]
## Expected Behavior
能否支持PreferenceFragmentCompat？PreferenceFragmentCompat里面也是RecyclerView，但是实际使用后默认的滚动条和fastscroll会同时出现
![image](https://user-images.githubusercontent.com/69662387/169471555-8b0e68b9-2450-4a11-8ff3-0a0219f0f28e.png)

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by allentown521** [comment]
补充一点，根布局是：CoordinatorLayout，使用了app:layout_behavior="com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior"

**Comment by allentown521** [comment]
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="?attr/colorSurface"
    android:fitsSystemWindows="true">
//PreferenceFragmentCompat嵌在这里view里面
    <androidx.fragment.app.FragmentContainerView
        android:id="@+id/settingsContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior"
        />

**Comment by allentown521** [comment]
通过设置recyclerView.setVerticalScrollBarEnabled(false);解决了，但是似乎不太适合短列表的滚动显示，滚动条长度是固定的

**Comment by allentown521** [comment]
列表滚动到底部后，滚动条没有滚动到底部

**Comment by zhanghai** [comment]
是的，你需要关闭自带的 scrollbar。这个库的滚动条长度是固定的，如果你想要变长的你可以用 RecyclerView 自带的 fastscroll（例如[这篇文章](https://medium.com/android-news/fast-scrolling-with-recyclerview-2b89d4574688)）。
