### ISSUE TITLE
增加隐藏的时间设置

### ISSUE THREAD

**Issue by allentown521** [zhanghai/AndroidFastScroll#46]
## Expected Behavior
现在打开界面后会显示，然后1.5s后隐藏，如果按钮太靠近滚动条区域，点击事件就被scrollbar消费了

## Actual Behavior
能否增加一个api可以设置自动隐藏的的时间，和默认隐藏的开关

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by zhanghai** [comment]
You should use an alternative `FastScroller.AnimationHelper` for this.

**Comment by zhanghai** [comment]
默认隐藏是标准的 Android 滚动条行为，目的是提醒用户列表是可以滚动的。由于屏幕大小不确定，很可能出现列表条目正好对准了屏幕下边缘导致看不出可以滚动的情况。

**Comment by allentown521** [comment]
你说的情况是一种提醒用户可以滚动的场景；现实是用户习惯已养成，无需刻意提示他可滚动，实时上很多app也是这样做的；
我意思是是否可以增加选项，来适应不同的需要，可以默认显示，但是可以关闭
