### ISSUE TITLE
能否动态获取recyclerview的内容高度

### ISSUE THREAD

**Issue by Gaoshaobin** [zhanghai/AndroidFastScroll#50]
## Steps to Reproduce the Problem

RecyclerViewHelper.java中getScrollRange中是通过mView.getPaddingTop() + itemCount * itemHeight + mView.getPaddingBottom();来计算ScrollRange，但是我们实际使用中用到了ConcatAdapter，就是同一个recyclerview中，有多种adapter，每种adapter中，列数是不一样的，而且itemView的高度也是不一样的，所以getScrollRange的计算方法不适用我们这种场景。  请问一下有什么比较好的解决方法吗？  另外，是否有考虑过通过mView.computeVerticalScrollRange()来代替itemCount * itemHeight吗（我这么试过，但是发现算出来的值不是固定的，滑动到底的时候，数值会变化）

## Specifications

- Version:
- Platform:

**Comment by zhanghai** [comment]
请阅读 README：

> The default ViewHelper implementation for RecyclerView supports both LinearLayoutManager and GridLayoutManager, but assumes that each item has the same height when calculating scroll, as there's no common way to deal with variable item height. If you know how to measure for scrolling in your specific case, you can provide your own ViewHelper implementation and fast scroll will work correctly again.
