### ISSUE TITLE
Bug: sample doesn't work well for ScrollView,NestedScrollView and WebView - almost nothing is shown

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zhanghai/AndroidFastScroll#6]
## Expected Behavior
To see a scrollable content with fast-scroller

## Actual Behavior
Almost nothing is shown

## Steps to Reproduce the Problem
1.Just switch to those places and try to scroll 

## Specifications

- Version:
VERSION=1.1.0
VERSION_CODE=6

- Platform:
Android Q but also before.

[device-2019-12-15-224309.zip](https://github.com/zhanghai/AndroidFastScroll/files/3965427/device-2019-12-15-224309.zip)

**Comment by zhanghai** [comment]
Tested the Play version of sample app (https://play.google.com/store/apps/details?id=me.zhanghai.android.fastscroll.sample) and it worked well on P. I used an Android Q emulator to test the release version before release as well so it should also be good. Your attached video is 50KB and only contains one frame, so I couln't really reproduce this anyhow...

**Comment by AndroidDeveloperLB** [comment]
No idea what happened to the video. Updated the file now, including an APK.
The version I tested is not on the Play Store but of the repository itself.

**Comment by zhanghai** [comment]
You attached an APK named `sample-debug.apk` which is not the Play version nor the APK downloaded from [Releases](https://github.com/zhanghai/AndroidFastScroll/releases), but seems to be an APK you built on your own computer. The reason why there isn't text is that, the text is actually [a symbolic link under res/raw](https://github.com/zhanghai/AndroidFastScroll/blob/master/sample/src/main/res/raw/license.txt) which links to the [LICENSE](https://github.com/zhanghai/AndroidFastScroll/blob/master/LICENSE) file in project root directory, and maybe you were building the APK on Windows which doesn't have symbolic link support and the link became a plain file. You can either try the pre-compiled sample APK, or if you want to try things locally, manually overwrite the link with a copy of the actual LICENSE file.

**Comment by AndroidDeveloperLB** [comment]
Why would you do such a thing for a sample on a public repository?
Why not put the files on the sample, so that it would work without linking?

Please fix this issue.

**Comment by zhanghai** [comment]
The file is in this repository, just that Windows doesn't support symbolic link. It was done this way mainly because of copyright issue, that I'm not 100% sure of the license of the text of Apache License itself so I had to keep it outside of the directories for source code.

**Comment by AndroidDeveloperLB** [comment]
So use Lorem ipsum content. Why even bother putting some text that you got from somewhere that might cause trouble?
