### ISSUE TITLE
Recyclerview Unexpected Scroll Behavior, Thumb invisible

### ISSUE THREAD

**Issue by kaisarturan** [zhanghai/AndroidFastScroll#8]
## Expected Behavior
Scroll thumb should be shown.

## Actual Behavior
Scroll thumb going invisible and unexpected behavior when item height is big.

## Steps to Reproduce the Problem

1. Create recyclerview and itemview height must be bigger than visible area
2. build with FastScrollerBuilder(recyclerView).build();
3. Now try to scroll problem is here.

## Specifications

- Version: 1.1.0
- Platform: Android 9

**Comment by zhanghai** [comment]
I couldn't reproduce this with an item height of `700dp`, larger than my screen height.

Do all your items have the same height? If not, it's not supported and you need to write your own `ViewHelper`.

Or if you are having too many very long items, you might be hitting a integer overflow or floating point arithmetics error, but we don't usually account for that...
