### ISSUE TITLE
PopupTextProvider#getPopupText(int position) should be @Nullable

### ISSUE THREAD

**Issue by tfonteyn** [zhanghai/AndroidFastScroll#9]
The interface PopupTextProvider:

    @NonNull <=====
    String getPopupText(int position);

But RecyclerViewHelper#getPopupText() accepts that getPopupText(int position) can return null.
i.e. that there is no popup text for that position.

Can I kindly propose you change the interface to

    @Nullable <=====
    String getPopupText(int position);

Android Studio's error reporting and myself would be grateful :)

**Comment by zhanghai** [comment]
It is non-null because if the interface is implemented, it should always return some text for the popup. Having the popup showing only some of the times is not supported. The helper can return null because the interface may not be implemented, in which case the popup is never sbown.
